version: "3"

networks:
  loki:

services:
  loki:
    container_name: loki
    build:
       context: .
       dockerfile: ./loki.Dockerfile
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    volumes:
      - loki-logs:/var/log
      - loki-storage:/storage
    restart: unless-stopped

  promtail:
    # image: grafana/promtail:2.7.4
    container_name: promtail
    build:
       context: .
       dockerfile: ./promtail.Dockerfile
    volumes:
      - promtail-logs:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    restart: unless-stopped

  grafana:
    container_name: grafana
    build:
       context: .
       dockerfile: ./grafana.Dockerfile
    volumes:
       - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - loki
    restart: unless-stopped

  syslog-ng:
      container_name: syslog-ng
      build:
         context: .
         dockerfile: ./syslog-ng.Dockerfile
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Australia/Sydney
      ports:
        - 514:5514/udp
        - 514:6601/tcp
      networks:
        - loki
      restart: unless-stopped

volumes:
  loki-storage:
  grafana-storage:
  loki-logs:
  promtail-logs:
