auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /storage/loki
  storage:
    filesystem:
      chunks_directory: /storage/loki/chunks
      rules_directory: /storage/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

compactor:
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 10

limits_config:
    retention_period: 4464h #aprox 6 month

ruler:
  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false
